version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - amper:amper
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier

  amper:
    image: amper-exporter/latest
    tty: true
    restart: always
    stdin_open: true
    env_file: ./amper-exporter/.env
    expose:
      - 9798
    ports:
      - 9798:9798
    devices:
      - "/dev/${SERIAL_PORT}:/dev/${SERIAL_PORT}"
    networks:
      - back-tier